In [79]:
import tensorflow as tf
import numpy as np

In [80]:
import pandas as pd 
df =pd.read_csv(r'C:\Users\kumaw\OneDrive\Desktop\offline\Data Science 16 june\sitp_16june-offline-\Deepl learning\ANN\cleaned_bikes.csv')

In [81]:
df

      Unnamed: 0     price  kms_driven  owner  age  power  brand
0              0   35000.0     17654.0    1.0  3.0  110.0      1
1              1  119900.0     11000.0    1.0  4.0  350.0      2
2              2  600000.0       110.0    1.0  8.0  675.0      3
3              3   65000.0     16329.0    1.0  4.0  180.0      1
4              4   80000.0     10000.0    1.0  3.0  150.0      4
...          ...       ...         ...    ...  ...    ...    ...
7319        9362   25000.0     48587.0    1.0  8.0  150.0      6
7320        9369   35000.0     60000.0    1.0  9.0  220.0      7
7321        9370  450000.0      3430.0    1.0  4.0  750.0     15
7322        9371  139000.0     21300.0    1.0  4.0  400.0      7
7323        9372   80000.0      7127.0    1.0  5.0  220.0      7

[7324 rows x 7 columns]

In [82]:
df.isnull().sum()

Unnamed: 0     0
price          0
kms_driven     0
owner         10
age            0
power          0
brand          0
dtype: int64

In [83]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [84]:
x =df.drop(['price'],axis=1)
y =df[['price']]

In [85]:
y

         price
0      35000.0
1     119900.0
2     600000.0
3      65000.0
4      80000.0
...        ...
7319   25000.0
7320   35000.0
7321  450000.0
7322  139000.0
7323   80000.0

[7324 rows x 1 columns]

In [86]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2)

In [87]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [88]:
input_shape =x_train.shape[1]
input_shape

5

In [89]:
model=Sequential()
model.add(Dense(units = 128, activation= 'relu',input_dim = input_shape))
model.add(Dense(units= 64,activation = "relu"))
model.add(Dense(units= 32,activation = "relu"))
model.add(Dense(units= 16,activation = "relu"))
model.add(Dense(units= 8,activation = "relu"))

model.add(Dense(units = 1,activation = "linear"))

model.compile(loss = 'mean_squared_error',optimizer = 'adam',metrics = ['mae','mse'])

c:\Users\kumaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [90]:
model.fit(x_train, y_train, epochs= 10, batch_size = 32)

Epoch 1/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 19681736704.0000 - mae: 82743.4375 - mse: 19682715648.0000
Epoch 2/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21429540864.0000 - mae: 83774.7500 - mse: 21430536192.0000
Epoch 3/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 21080702976.0000 - mae: 80957.2891 - mse: 21081804800.0000
Epoch 4/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 23103275008.0000 - mae: 67859.0078 - mse: 23104174080.0000
Epoch 5/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13034429440.0000 - mae: 53538.3008 - mse: 13034616832.0000
Epoch 6/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13779313664.0000 - mae: 59391.3438 - mse: 13779990528.0000
Epoch 7/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15280051200.0000 - mae: 59752.8438 - mse: 15280777216.0000
Epoch 8/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 15125005312.0000 - mae: 58482.2227 - mse: 15125689344.0000
Epoch 9/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13310363648.0000 - mae: 56644.8906 - mse: 13310999552.0000
Epoch 10/10
184/184 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14123595776.0000 - mae: 59214.0312 - mse: 14124258304.0000

In [91]:
pred=model.predict(x_test)

46/46 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [92]:
# pred =np.ravel(pred )

In [93]:
pred =pd.DataFrame(pred)

In [94]:
y_test

         price
5252  180000.0
5181   38700.0
3299   21000.0
7099  105000.0
2660  135000.0
...        ...
3043   30000.0
6391   75000.0
5165   25000.0
7269   70000.0
2551   16000.0

[1465 rows x 1 columns]

In [95]:
pred

                 0
0     86295.296875
1     86295.296875
2     86295.296875
3     86295.296875
4     86295.296875
...            ...
1460  86295.296875
1461  86295.296875
1462  86295.296875
1463  86295.296875
1464  86295.296875

[1465 rows x 1 columns]

In [96]:
y_test

         price
5252  180000.0
5181   38700.0
3299   21000.0
7099  105000.0
2660  135000.0
...        ...
3043   30000.0
6391   75000.0
5165   25000.0
7269   70000.0
2551   16000.0

[1465 rows x 1 columns]

In [97]:
pd.concat([y_test, pred], axis = 1)

         price             0
5252  180000.0           NaN
5181   38700.0           NaN
3299   21000.0           NaN
7099  105000.0           NaN
2660  135000.0           NaN
...        ...           ...
1460       NaN  86295.296875
1461       NaN  86295.296875
1462       NaN  86295.296875
1463       NaN  86295.296875
1464       NaN  86295.296875

[2621 rows x 2 columns]

In [98]:
# output =pd.DataFrame({'actual':y_test,"predication":pred})

In [ ]:
# pd.concat(['y_test', 'pred'], axis = 1)

TypeError: cannot concatenate object of type '<class 'str'>'; only Series and DataFrame objs are valid